### ISSUE TITLE
HAS_ONE, BELONGS_TO: together=false no give effect

### ISSUE THREAD

**Issue by TheHett** [yiisoft/yii#2681]
Hi,
why yii do not support separated loading data for BELONGS_TO and HAS_ONE relations?

**Comment by thesame-** [comment]
Sorry for bumping this old issue. 
> Option “together=false” makes no sense for the “HAS_ONE” and “BELONGS_TO” relations. If you do not want the related records be fetched with the main table at single query, you can simply do not use “with”.

I believe there is a use case for `together = false` in `BELONGS_TO` and `HAS_ONE`. 

So I have this scenario, where I have paired invoices. Invoice model is related to itself as child. If I would try to load invoice with its items and its related invoice and items, I would get `Not unique table/alias: 'items'.`.

```
class Invoice extends CActiveRecord
{
    public function relations()
    {
        return array(
            'items' => array(self::HAS_MANY, 'InvoiceItem', 'invoice_id'),
            'child' => array(self::HAS_ONE, 'Invoice', 'parent_id'),
            'parent' => array(self::BELONGS_TO, 'Invoice', 'parent_id'),
    }
}
```
To avoid alias conflict, I would prefer this syntax as it seem to be more readable to me:
```
$criteria = new CDbCriteria;
$criteria->with = array(
    'items',
    'items.meta',
    'items.product',
    'items.service',
    'child' => array(
        'together' => false,
        'with' => array(
            'items',
            'items.meta',
            'items.product',
            'items.service',
        ),
    ),
);

$criteria->addColumnCondition(array('t.parent_id' => null));
$criteria->limit = 100;
Invoice::model()->findAll($criteria);
```
Rather than doing this:

```
$criteria = new CDbCriteria;
$criteria->with = array(
    'items',
    'items.meta',
    'items.product',
    'items.service',
    'child' => array(
        'with' => array(
            'items' => array(
                'together' => false,
                'with' => array(
                    'meta',
                    'product',
                    'service',
                ),
            ),
        ),
    ),
);

$criteria->addColumnCondition(array('t.parent_id' => null));
$criteria->limit = 100;
Invoice::model()->findAll($criteria);
```
Is there a better way for achieving desired result?
