### ISSUE TITLE
XSS on YII_CSRF_TOKEN

### ISSUE THREAD

**Issue by vikasprogrammer** [yiisoft/yii#2961]
If a user is somehow able to spoof the YII_CSRF_TOKEN and appends something like "><script>alert(1)</script> to it. It will be reused by the form on a web page and XSS will execute. 

I think the TOKEN should sanitized after its sent from the browser. Please specify a solution. 

PS: Sorry for sending another XSS your way.

**Comment by SimonWaters** [comment]
Was doing some security testing of an application that is (still) using Yii 1.1.13 and found this issue. My reading of the code is the relevant sections are unchanged in Github.

It appears to rely on the developer or deployer of the framework to prevent a cookie poisoning attack to get a XSS attack against sites using Yii 1.1. I've not tried poisoning my own cookies yet.

The obvious fix to me is for function getCsrfToken to check the cookie->value retrieved contains only hexadecimal characters and force a new CSRF token to be generated if it does not, which will avoid it propagating a corrupted value of any consequence into the form, and triggering a XSS down the line when a form is presented.

I agree it relies on the application programmer, and/or the deployer, doing something sub-optimal. But the application I'm looking at is vulnerable to these types of attack because of the use of YII framework CSRF feature, and we want security features that don't make things worse.

**Comment by SimonWaters** [comment]
Oops sorry for earlier comment, realise it is more complex that I first thought. However this application still has JavaScript injected via YII_CSRF_TOKEN, so I think validating the CSRF token when it is read from cookie to contain hexadecimals makes sense for the application I'm looking at. They do refer to the token directly in their own code, so I'll go see if the it is the application or framework that is responsible.
