### ISSUE TITLE
CGridView should have an option to only select/unselect rows by clicking on checkboxcolumn checkbox rather than anywhere in row

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#3045]
In a CGridView with selectableRows>1, by clicking anywhere on a row, you select it.
While this is wonderful to have this behavior as an option, and even OK to have it as a default, it's terribly annoying that you cannot disable it.

There should exist an option to disable it, so that only by clicking on a checkbox belonging to a checkboxcolumn you would select a row. 

It should be a property of CGridView. When true (default), rows would be selected by clicking anywhere within a row; when false, only clicking on checkboxcolumn checkboxes would select rows

**Comment by Sibilino** [comment]
Is there still interest for this feature? It appears that the row selection function triggers from *tbody > tr* but that could be made configurable.

Why only on selectableRows > 1 though? Even with a single selectable row, it can be anoying to click on a row in order to copy some content and then have the row selected automatically.

Anyways, I already have some quick code to fix this issue on my app. Should I take the time to clean it up and make a pull request?

**Comment by samdark** [comment]
Yes, issue is still open so a pull request would be appropriate.
