### ISSUE TITLE
route site/captcha doesn't show an image

### ISSUE THREAD

**Issue by supergao222** [yiisoft/yii#3403]
when I visit http://localhost/app/?r=site/captcha, it only show some string in browser.
In the google chrome console, I find that the site/captche route return a Content-type of "text/html", not "image/png"

**Comment by rschip** [comment]
I had problems of getting the captcha picture in the backend of yii2. The model was placed under common because we use login in the front- and back-end, it works in the frontend out of the box but not in the backend. I used the following workaround:
In the backend/site/login.php
I replaced:

    <?=
        $form->field($model, 'verifyCode')->widget(Captcha::className(), [
        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}     </div></div>',])
    ?>

With:

    <?php
        $tag = $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}    </div></div>',]);
        $tag = preg_replace('/backend/', 'frontend', $tag);
        echo $tag;
    ?>

**Comment by samdark** [comment]
@rschip this is Yii 1.1 issue tracker.

**Comment by rschip** [comment]
Hello Alexander,

I posted the workaround in the yii2 thread, sorry, I'm pretty new here.

**Comment by samdark** [comment]
Closing since it's not that important.
