### ISSUE TITLE
CActiveDataProvider bug with multiple many_to_many relations

### ISSUE THREAD

**Issue by vnenkpet** [yiisoft/yii#3753]
While using "with" and multiple many_to_many or has_many relations, the item count and retrieved items in CActiveDataProvider are wrong. 
For example, if I have a table that has 66 items in total, while using CActiveDataProvider and CListView with pagination and $criteria->with for multiple many_to_many relations (like `$criteria->with('many_to_many1', 'many_to_many2');` ), I only get about 25 items (the number depends on the relations I guess). The "totalItemCount" and page count are right, but the items on page are less than there should be.
As far as I know this problem is still present in Yii 2 as well.

**Comment by vnenkpet** [comment]
It's actually present even on one many_to_many relation. It probably doesn't take the relations in account when counting a page limit.

**Comment by nineinchnick** [comment]
Does it work with `HAS_MANY`? Do you use `together`?

CActiveDataProvider indexes fetched models using the `keyAttribute` property.

**Comment by vnenkpet** [comment]
I am using it with together == true. I now understand why it works like this after reading several articles, but should not it still be considered an issue? It's definitely not an expected behavior and we would like to be able to use single query due to performance reasons even on this kind of complicated relations in CGridView etc.

**Comment by vnenkpet** [comment]
https://github.com/yjeroen/ManyMany/blob/master/protected/components/KeenActiveDataProvider.php This is an extension that actually works as expected with complicated relations. Wouldn't it be a good idea to implement the same functionality to the default CActiveDataProvider?

**Comment by georaldcamposano** [comment]
Is this the problem where you would get weird pagination numbers like "1 - 4 of 30 results" instead of "1 - 10 of 30"? A lot of people seem to run into this problem.

Anyway if that's the case, here's my explanation of why this happens:

http://www.yiiframework.com/forum/index.php/topic/58192-cgridview-filtering-and-sorting-on-has-many-relations/page__p__264915#entry264915

**Comment by vnenkpet** [comment]
Well from my point of view as the framework user, having from items in pagination in CActiveDataProvider is definitely not an expected behavior.

**Comment by georaldc** [comment]
I think with the way yii builds out the queries, it can't execute the whole thing in 1 go and apply a limit/offset. Normally, not using ```together``` should get this to work but Yii ends up using 2 + n (number of relations specified using ```with```) queries to achieve the result when pagination comes into play.

Maybe a developer can chime in with some ideas. There might be other ways to do this (since I run into the same problem too from time to time)

**Comment by nineinchnick** [comment]
When you add a join to a table, the results will contain duplicate rows of the main table for which there are more than one row in joined table. The dataProvider removes those duplicates reducing the number of rows drawn in the grid.

This is more of a SQL issue than Yii. Using `together` here instead of normal eager loading which would perform two queries is not always faster, that depends on the results size and number.

**Comment by nineinchnick** [comment]
So apparently it's related to #2360.
