### ISSUE TITLE
bug with two CDbCacheDependency

### ISSUE THREAD

**Issue by nicdnepr** [yiisoft/yii#3754]
here is two functions

  public function getTreeviewData()
    {
         $dependency = new CDbCacheDependency('SELECT MAX(update_time) FROM Category');
         $categorys = $this->cache(Yii::app()->params->cacheTime, $dependency)->with('children')->findAllByAttributes(['parent_id' => 0]);

```
    $data = [];
    foreach ($categorys as $category) {

        $children = [];

        foreach($category->children as $child) {
            $children[] = [
                'text' => CHtml::link($child->name, ['category/index', 'code'=>$child->code]),
            ];
        }

        $data[] = [
            'text' => CHtml::link($category->name, ['category/index', 'code'=>$category->code]),
            'children' => $children
        ];

    }

    return $data;
}

public function getList($code = null)
{
    $criteria = new CDbCriteria();
    $criteria->with = ['category', 'categorys'];
    $criteria->together = true;
    $criteria->condition = 't.paid = 1 AND t.active = 1 AND t.expiry_date > NOW()';
    $criteria->order = 't.seo2 DESC, t.seo1 DESC, t.expiry_date DESC';

    $criteria2 = new CDbCriteria;
    $criteria2->compare('categorys.code', $code);
    $criteria2->compare('category.code', $code, false, 'OR');
    $criteria->mergeWith($criteria2);

    $dependency = new CDbCacheDependency('SELECT MAX(update_time) FROM Advert');
    $dataProvider = new CActiveDataProvider($this->cache(Yii::app()->params->cacheTime, $dependency, 2), [
        'criteria'=>$criteria
    ]);

    return $dataProvider;
}
```

getTreeviewData calls first, getList calls second, but in getList cache don't work, even CDbCacheDependency not called. i can even put any table name into CDbCacheDependency without error. 
but if i remove getTreeviewData then cache works fine in getList

**Comment by georaldcamposano** [comment]
I tested similar code as what you had and both functions worked just fine caching data

**Comment by nicdnepr** [comment]
i can add some information
here is view
>><?php
/* @var $this CategoryController */
/* @var $dataProvider CActiveDataProvider */
$this->pageTitle = Yii::app()->name;
?>
    <?php $this->widget('CTreeView', [
        'data'=>Category::model()->getTreeviewData(),
        'collapsed'=>true,
        'persist'=>'location',
    ]) ?>
    <?php $this->widget('zii.widgets.CListView', array(
        'dataProvider'=>$dataProvider,
        'itemView'=>'/advert/_view',
    )); ?>

in this case cache not work

but this code is worked!!
>><?php $this->widget('zii.widgets.CListView', array(
        'dataProvider'=>Advert::model()->getList(),
        'itemView'=>'/advert/_view',
    )); ?>

and this code is work!(swap blocks)
>><?php $this->widget('zii.widgets.CListView', array(
        'dataProvider'=>$dataProvider,
        'itemView'=>'/advert/_view',
    )); ?>
<?php $this->widget('CTreeView', [
        'data'=>Category::model()->getTreeviewData(),
        'collapsed'=>true,
        'persist'=>'location',
    ]) ?>

**Comment by georaldcamposano** [comment]
I copied your code as close as possible and cache worked fine for both method calls. Maybe try deleting the cache keys being called in your database and see if that helps.

**Comment by nicdnepr** [comment]
here is test code https://yadi.sk/d/mv9Q5hGdeoBeF with database
look at site/index
>>'dataProvider'=>$dataProvider, //cache don't work
        //'dataProvider'=>Advert::model()->getList(), //cache work

**Comment by georaldc** [comment]
Ok, I see the problem now. Here is what I think is happening (and someone please correct me if I am wrong):

When you first call ```$dataProvider = Advert::model()->getList();``` inside your controller action, the method sets up the Advert model to have its database queries cached.

```
$dependency = new CDbCacheDependency('SELECT MAX(update_time) FROM Advert');
$dataProvider = new CActiveDataProvider($this->cache(100, $dependency, 2), [
	'criteria'=>$criteria,
]);
```

If you look at the source code, ```CActiveRecord::cache()``` passes its parameters to the cache method of the ```CDbConnection``` connection used by the model. What's happening here is that Yii will be ready to cache the next 2 queries that will be run against this database connection. These queries you expect from Advert will be executed once you actually use ```$dataProvider``` variable inside your ```CListView``` widget in your view file, which would generate a Count query and the actual select query.

The problem is before you do that, you called the following:

```Category::model()->getTreeviewData()```

which again sets up a dependency and attempts to cache your findAll() code:

```
$dependency = new CDbCacheDependency('SELECT MAX(update_time) FROM Category');
$categorys = $this->cache(100, $dependency)->findAllByAttributes(['parent_id' => 0]);
```

The reason why query caching stops working after this is because this new cache call replaces your initial cache settings which came from ```Advert::model()->getList()```, and it not having a query count value means that it will use the default value of 1. So yii caches your Category findAll() and stops caching after that. It working again by calling your getList() function after is because the database connection's cache method gets called again with new attributes.

Hopefully my understanding was correct and it explains why you were running into problems.

**Comment by nicdnepr** [comment]
thanks, now it's clear
