### ISSUE TITLE
No exception stack trace in Yii 1.1.16

### ISSUE THREAD

**Issue by ua2004** [yiisoft/yii#3760]
After updating to Yii 1.1.16 error pages now don't show the full stack trace which was convenient. Now it just renders a regular view with only an error message. How do I switch to a former exception page? Am I doing something wrong?

**Comment by nineinchnick** [comment]
Make sure you have YII_DEBUG set to true.

**Comment by ua2004** [comment]
It is true, of course.

**Comment by samdark** [comment]
Related to https://github.com/yiisoft/yii/pull/2903

**Comment by samdark** [comment]
`errorAction` has more priority than `YII_DEBUG` so if you have it you'll get error page instead of stacktrace.

**Comment by ua2004** [comment]
@samdark, finally! Thank you! Was this behavior changed in 1.1.16?

**Comment by samdark** [comment]
Yes, it was changing there and forth starting from 1.1.12. I think we need to stick with current one documenting it better and providing solution to have old good behavior as well:

```php
'errorAction' => YII_DEBUG ? null : 'site/error';
```

**Comment by yii-user** [comment]
@samdark's fix above works, however now `CHttpException` (error 400) is output in stack trace rather than `errorAction`

**Comment by smcelveen** [comment]
Where does does @samdark fix go?

**Comment by samdark** [comment]
In config.

**Comment by smcelveen** [comment]
Sheesh, thanks. A bit more literal:
```php
    'errorHandler'=>array(
        'errorAction' => YII_DEBUG ? null : 'site/error',
    ),
```

**Comment by trejder** [comment]
@samdark Just to feed my curiosity... any information or argument, why it was changing there and forth from version to version? Who decided about change, and by what that decision was influenced?

I'm asking, because current implementation seems strange to me. Printing out only one-line error message in `errorAction` view seems pretty useless in debug mode. The way it was handled before (`YII_DEBUG` overrides everything everywhere and decision, how error is rendered, is made internally) sounds far better to me.

What decided for current soltion -- the need to change `errorAction` as you showed, seems strange. Who needs non-full-stack errors, when `YII_DEBUG` is enabled?
