### ISSUE TITLE
Tests are failing on PHP7

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii#3995]
https://travis-ci.org/yiisoft/yii/jobs/94242787#L139

**Comment by tomtomsen** [comment]
it seems that php7 throws now a ParseError if an eval statement ist invalid. (https://secure.php.net/manual/de/migration70.incompatible.php).

could be quiet tricky to fix that. should a class ParseError be written (if !class_exists)? would that be an option?

**Comment by farmani** [comment]
@cebe any news about release date? I really like to test my new project written by yii1 on php7.
thanks for you hard working

**Comment by cebe** [comment]
We have not set a date for 1.1.17 yet but we'll try do fix this asap

**Comment by samdark** [comment]
Fixed https://github.com/yiisoft/yii/commit/5be58254ef12be5f6d67cc8ea44fdc11c80c633a

**Comment by cebe** [comment]
:+1:

**Comment by softark** [comment]
There are 2 more "@eval()"s in the framework code that may cause incompatibility in PHP 7.

1. CTimestampBehavior.php
2. CChoiceFormat.php

And we have to modify the following script to skip installing memcache on PHP 7 as we are doing for yii 2, otherwise travis-ci will fail.

- tests/travis/memcache-setup.sh

I'm gonna make a PR.

**Comment by samdark** [comment]
Good. Waiting forward for it.

**Comment by softark** [comment]
Here it is.
https://github.com/yiisoft/yii/pull/3998

But I failed to connect the PR with this issue. Sorry.
