### ISSUE TITLE
INI directive session.entropy_length is removed since PHP 7.1

### ISSUE THREAD

**Issue by My6UoT9** [yiisoft/yii#4233]
According to https://secure.php.net/manual/en/session.configuration.php#ini.session.entropy-length
That directive does not exist anymore.

In CSecurityManager it is used 
```
    /**
      * Get random bytes from the system entropy source via PHP session manager.
     * @return boolean|string 20-byte random binary string or false on error.
     * @since 1.1.14
     */
	public function generateSessionRandomBlock()
	{
		ini_set('session.entropy_length',20);
		if(ini_get('session.entropy_length')!=20)
			return false;
```

Is this a problem, or is it irrelevant?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.20
| PHP version      | 7.2

**Comment by phena109** [comment]
By just reading the code, it seems that there is a fallback for the random number generation. Instead of using the `generateSessionRandomBlock()` function, it will use `generateSessionRandomBlock()`.

My personal opinion is, it should not be a problem because it has a fallback. Also, Yii 1.1 branch will need to maintain BC to PHP 5.1 and above so that portion of code is likely to stay for that reason.

**Comment by ddziaduch** [comment]
Does this component event work? It required mcrypt which was deprected in 7.1 and removed in 7.2 🤔

**Comment by My6UoT9** [comment]
Yes this works fine, as @phena109 commented. As the algorithm checks for existence of mcrypt first, before using it.
