### ISSUE TITLE
Notice Method ReflectionParameter::isArray() is deprecated в CAction.php:97 on php 8.0.1

### ISSUE THREAD

**Issue by emenshov** [yiisoft/yii#4342]
### What steps will reproduce the problem?
Run any controller action with parameters

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.23
| PHP version      | 8.0.1
| Operating system |

**Comment by emenshov** [comment]
![image](https://user-images.githubusercontent.com/76549649/106445507-27290500-6490-11eb-9ba8-e1acd00efc7a.png)

**Comment by marcovtwout** [comment]
@emenshov Could you please update this issue to english?

**Comment by emenshov** [comment]
> @emenshov Could you please update this issue to english?

done

**Comment by marcovtwout** [comment]
Thank you - I will investigate both issues later this week.

**Comment by b1rdex** [comment]
The issue is here: https://github.com/yiisoft/yii/commit/84235713bcaddb10fcd0daf7100f3d64753b2aa7#diff-48c3f2514cdc31bf4e43c0455c58951206dafaa01754543bdc1108283512f689R97
It should be `if(version_compare(PHP_VERSION,'8.0','>=') >= 0) {`. Looks like other version comparisons in the mentioned commit need fixing too.

**Comment by rob006** [comment]
`version_compare(PHP_VERSION,'8.0','>=')` should return boolean according to [docs](https://www.php.net/manual/en/function.version-compare.php), so this condition looks fine.

**Comment by b1rdex** [comment]
@rob006 you're absolutely right!

**Comment by rob006** [comment]
I suspect that OP is using 1.1.22 instead of 1.1.23 - line number from error match file from 1.1.22: https://github.com/yiisoft/yii/blob/1.1.22/framework/web/actions/CAction.php#L97
In 1.1.23 `isArray()` is called in different line: https://github.com/yiisoft/yii/blob/1.1.23/framework/web/actions/CAction.php#L100

**Comment by marcovtwout** [comment]
@rob006 I think you are correct.
@emenshov Could you confirm you are working on 1.1.23?

**Comment by emenshov** [comment]
> @rob006 I think you are correct.
> @emenshov Could you confirm you are working on 1.1.23?

You're right. I made a mistake. My apologize. Everything is fine in version 1.1.23. I will close the issue
