### ISSUE TITLE
Decimal field validation is shorter than the database can handle

### ISSUE THREAD

**Issue by joshbmarshall** [yiisoft/yii#4376]
### What steps will reproduce the problem?
Create a decimal(6,2) field in the database. Try entering 1234.56 into a text field. 

### What is the expected result?
Validation is ok.

### What do you get instead?
Validation will say it is too long.

### Additional info

Fixed in PR #4375

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.24
| PHP version      | 7.4
| Operating system | Linux

**Comment by marcovtwout** [comment]
@joshbmarshall Could you explain or provide a code sample what you mean with "validation"?

**Comment by joshbmarshall** [comment]
My apologies. The number field that is created uses the validator's max field for the maxlength, so I can't actually type a number long enough to show the validator error in the CForm.
e.g. in CHtml::activeInputField you can see that the maxlength is set to $validator->max

The max value is taken from the 6 of decimal(6,2) and so doesn't take the '.' into account and allow the field length to be 7.

Does that make sense?

**Comment by joshbmarshall** [comment]
Yes this is correct the code generated with Gii has max length set one char too short. The proposed fix is in #4375

**Comment by marcovtwout** [comment]
I thought so, but in that case CDbColumnSchema is not the correct place to fix this. You should locate the code in Gii that you think is wrong and apply the change there.

**Comment by rob006** [comment]
@marcovtwout I think that purpose of `size` property is to keep length of the column, I don't think it is used by anything except Gii.

**Comment by marcovtwout** [comment]
I looked up the piece of code that I was talking about: gii's ModelCode function generateRules(): https://github.com/yiisoft/yii/blob/master/framework/gii/generators/model/ModelCode.php#L220
This converts the table schema metadata into Yii's validation rules and this is where you expect the length to be set to 7.

The `CDbColumnSchema->$size` of 6 is technically correct: with a `DECIMAL(6,2)` that first digit (the precision) is 6 and that is the number of digits that will be stored. This is the same in Yii2. Only when dealing with user input you want that extra character to allow a separator.

And even though Yii internally only uses `$size` in the Gii-module, the metadata is publicly exposed via methods such as ActiveRecord->getTableSchema() so we cannot change it for backwards compatbility.

So it should be fixed in generateRules() but that's not trivial, since Yii sees MySQL Decimal as a string and treats those all the same way: https://github.com/yiisoft/yii/blob/master/framework/gii/generators/model/ModelCode.php#L240

**Comment by marcovtwout** [comment]
I propose to close this as a wontfix - this issue is a trivial enhancement and not easy to improve.
