### ISSUE TITLE
Hidden fields generated by CHtml::beginForm()

### ISSUE THREAD

**Issue by joujou** [yiisoft/yii#579]
I have a CActiveForm using get method.
When I submit the form (to the same page), hidden fields are generated, one for each field of my form.
If I submit the form again, my fields are submitted, plus the hidden fields added. When back on the page, hidden fields are generated for the hidden fields, and so on, submit after submit, the number of hidden fields grows up.
Is it normal, I am doing something wrong ?

**Comment by velosipedist** [comment]
I think, the problem is that beginForm() behavior is not expected by default, and adding action attribute is just undocumented hack. Maybe, it worth to be documented in phpdoc at least?

Optionally, why not to make special option passing into $htmlAttributes, like `enableHiddenQueryParams` and make it true by default, for keeping BC?

**Comment by cebe** [comment]
@velosipedist this issue is really old and actually has been solved. please open a new issue if you think there is a bug or improvement needed.
